# Generated by Django 3.2.9 on 2022-04-28 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='异常类型')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Abnormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='表型/临床指征', max_length=100, verbose_name='表型')),
                ('karyotype', models.CharField(help_text='遵循ISCN2020描述的核型输入', max_length=30, verbose_name='核型描述')),
                ('broken_site', models.CharField(blank=True, help_text='断裂点位（可选）', max_length=30, null=True, verbose_name='断裂点位')),
                ('fragile_site', models.CharField(blank=True, help_text='脆性位点（可选）', max_length=30, null=True, verbose_name='脆性位点')),
                ('chromosome', models.CharField(choices=[('1', '1号染色体'), ('2', '2号染色体'), ('3', '3号染色体'), ('4', '4号染色体'), ('5', '5号染色体'), ('6', '6号染色体'), ('7', '7号染色体'), ('8', '8号染色体'), ('9', '9号染色体'), ('10', '10号染色体'), ('11', '11号染色体'), ('12', '12号染色体'), ('13', '13号染色体'), ('14', '14号染色体'), ('15', '15号染色体'), ('16', '16号染色体'), ('17', '17号染色体'), ('18', '18号染色体'), ('19', '19号染色体'), ('20', '20号染色体'), ('21', '21号染色体'), ('22', '22号染色体'), ('X', 'X染色体'), ('Y', 'Y染色体')], help_text='涉及染色体', max_length=2, verbose_name='涉及染色体')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('abnormal_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='abnormal', to='chromosome.abnormaltype')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
