# Generated by Django 3.2.9 on 2022-04-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chromosome', '0005_reference_abnormal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='abnormal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='chromosome.abnormal'),
        ),
    ]
