# Generated by Django 3.2.9 on 2022-05-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromosome', '0006_alter_reference_abnormal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnormal',
            name='description',
            field=models.CharField(help_text='表型/临床指征', max_length=150, verbose_name='表型'),
        ),
        migrations.AlterField(
            model_name='abnormal',
            name='karyotype',
            field=models.CharField(help_text='遵循ISCN2020描述的核型输入', max_length=150, verbose_name='核型描述'),
        ),
    ]
