# Generated by Django 3.2.9 on 2021-11-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='last_created_time',
            new_name='last_updated_time',
        ),
    ]
