# Generated by Django 3.2.9 on 2021-11-28 07:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211128_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='motto',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
