# Generated by Django 3.2.9 on 2022-01-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='readed_num',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
